### ISSUE TITLE
Timestamp contains error stack trace 

### ISSUE THREAD

**Issue by superTes** [allure-framework/allure-mocha#44]
Could not read result ./allure-results/4818fc57-a8b0-4f82-8c21-3845cbfd53df-testsuite.xml: {}
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `long` from String "1524727276540 TimeoutError: Confirm modal should appear                 Wait timed out after 10230ms": not a valid Long value
 at [Source: (sun.nio.ch.ChannelInputStream); line: 67, column: 17] (through reference chain: ru.yandex.qatools.allure.model.TestSuiteResult["test-cases"]->java.util.ArrayList[0]->ru.yandex.qatools.allure.model.TestCaseResult["steps"]->java.util.ArrayList[4]->ru.yandex.qatools.allure.model.Step["stop"])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1535)
        at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:910)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer._parseLong(NumberDeserializers.java:584)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:557)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:535)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at io.qameta.allure.allure1.ListDeserializer.deserialize(ListDeserializer.java:56)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at io.qameta.allure.allure1.ListDeserializer.deserialize(ListDeserializer.java:56)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3058)
        at io.qameta.allure.allure1.Allure1Plugin.readXmlTestSuiteFile(Allure1Plugin.java:432)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at io.qameta.allure.allure1.Allure1Plugin.readResults(Allure1Plugin.java:116)
        at io.qameta.allure.ReportGenerator.lambda$readResults$0(ReportGenerator.java:32)
        at java.util.ArrayList.forEach(ArrayList.java:1255)
        at io.qameta.allure.ReportGenerator.readResults(ReportGenerator.java:32)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:54)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:43)
        at io.qameta.allure.Commands.generate(Commands.java:88)
        at io.qameta.allure.Commands.serve(Commands.java:112)
        at io.qameta.allure.CommandLine.run(CommandLine.java:136)
        at java.util.Optional.orElseGet(Optional.java:267)
        at io.qameta.allure.CommandLine.main(CommandLine.java:72)

**Comment by just-boris** [comment]
Could you share a sample code that reproduces the issue?

**Comment by just-boris** [comment]
According to this line

```
ru.yandex.qatools.allure.model.TestSuiteResult["test-cases"]->java.util.ArrayList[0]->ru.yandex.qatools.allure.model.TestCaseResult["steps"]->java.util.ArrayList[4]->ru.yandex.qatools.allure.model.Step["stop"]
```

The problem is in the stop time of some step. How do you use `allure.createStep` function?

**Comment by superTes** [comment]
@just-boris can you check PR, please?  https://github.com/allure-framework/allure-js-commons/pull/35

**Comment by just-boris** [comment]
I checked. If the problem is related to Mocha framework, it must be investigated and checked here first.

The good first step would be reproducing the issue.
