### ISSUE TITLE
Adapter failure due to XML unaccepted character

### ISSUE THREAD

**Issue by KiT-Maverik** [allure-framework/allure-mocha#56]
Hi!
Борис, вызываю тебя) @just-boris
Looks like I've found a bug.

TECH
- mocha 3.2.0
- pact 7.0.2
- mocha-allure-reporter 1.4.0
- allure-commandline 2.9.0

When pact veriification fails (in my case with 100% chance), allure reporter fails to (allure-results are not generated)
```
Internal error in Allure: Error: charData should not contain characters not allowed in XML
    at XmlCharData.set [as charData] (/home/kit/dev/projects/pact/pact-sandbox/node_modules/xmlcreate/lib/nodes/XmlCharData.js:75:23)
    at new XmlCharData (/home/kit/dev/projects/pact/pact-sandbox/node_modules/xmlcreate/lib/nodes/XmlCharData.js:53:24)
    at XmlElement.charData (/home/kit/dev/projects/pact/pact-sandbox/node_modules/xmlcreate/lib/nodes/XmlElement.js:168:28)
    at parseString (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:53:27)
    at parseValue (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:227:5)
    at parseObjectOrMapEntry (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:132:5)
    at parseObjectOrMap (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:152:13)
    at parseValue (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:220:9)
    at parseObjectOrMapEntry (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:132:5)
    at parseObjectOrMap (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:152:13)
    at parseValue (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:220:9)
    at /home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:192:9
    at Array.forEach (<anonymous>)
    at parseArrayOrSet (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:187:16)
    at parseValue (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:224:9)
    at parseObjectOrMapEntry (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:132:5)
    at parseObjectOrMap (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:152:13)
    at parseValue (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:220:9)
    at parseObjectOrMapEntry (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:132:5)
    at parseObjectOrMap (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:152:13)
    at parseValue (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:220:9)
    at parseToDocument (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:249:5)
    at Object.parse (/home/kit/dev/projects/pact/pact-sandbox/node_modules/js2xmlparser/lib/main.js:265:20)
    at Object.writeSuite (/home/kit/dev/projects/pact/pact-sandbox/node_modules/allure-js-commons/writer.js:9:83)
    at Allure.endSuite (/home/kit/dev/projects/pact/pact-sandbox/node_modules/allure-js-commons/index.js:36:16)
    at Runner.<anonymous> (/home/kit/dev/projects/pact/pact-sandbox/node_modules/mocha-allure-reporter/index.js:35:24)
    at Runner.<anonymous> (/home/kit/dev/projects/pact/pact-sandbox/node_modules/mocha-allure-reporter/index.js:23:32)
    at Runner.emit (events.js:203:15)
    at /home/kit/dev/projects/pact/pact-sandbox/node_modules/mocha/lib/runner.js:659:14
    at next (/home/kit/dev/projects/pact/pact-sandbox/node_modules/mocha/lib/runner.js:295:14)
    at Immediate._onImmediate (/home/kit/dev/projects/pact/pact-sandbox/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by KiT-Maverik** [comment]
@just-boris 

Hi!
I've added a sandbox project in order to simplify bug reproduction.
Notify me if it helps.

**Comment by baev** [comment]
@KiT-Maverik please consider possibility to switch to a new `allure-mocha` integration https://www.npmjs.com/package/allure-mocha

This one most likely will not be updated any more. All issues related to new integration can be reported in new repo located here https://github.com/allure-framework/allure-js/issues
